### PR TITLE
WIP: Renderable pattern for Scene

### PR DESCRIPTION
**Pull request by shyamd**
This is a WIP PR to implement the `Renderable` pattern.
`Renderable` is an abstract base class that all interfaces that convert a given `type` to `Scene` should implement. By doing this, they will automatically plugin as the converter into the `RenderableMeta` registry.

### CODE REVIEW

**Comment by shyamd** [comment]
So, I initially thought the interfaces should be classes because we may want to have "static" parameters that we can change in the interface and have those reflected in how they convert the objects into Scenes. It looks like the object->Scene process is mostly just as single method. Do you see a time when it needs to be more complex?

**Comment by mkhorton** [comment]
From an external point of view, I think it should just be a single method (`get_scene` or `to_scene`), I'm not sure when it might be more complicated. Do you have a specific example in mind? It might help clarify.

**Comment by shyamd** [comment]
I don't understand why my PR doesn't understand committed PRs right now.

Renderable pattern mostly works now. The big issue that the Site and Structure functions don't test properly because I have no clue what display_color and display_radius are supposed to be like.

**Comment by mkhorton** [comment]
They're site properties for colors (given as "#rrggbb" strings) and radii (floats) respectively, they're lists of lists because each site can hold multiple species/occu so can have multiple colors. I'm not happy with this to be honest. It is really helpful for this data to travel with the site itself for the sole reason that it makes it really simple for a user to specifically override the color on a given site. Alternative ideas included a specie property (would require a pymatgen modification), generated dynamically as a function taking a single specie (would not play nicely when color-coding by site properties), generated dynamically as a function taking a sitecollection (probably the best, but would not give an easy way for user to over-ride specific site).

**Comment by shyamd** [comment]
One option is to implement some sort of singleton that holds defaults and the renderer uses that if it finds no local display properties. That way by modifying the color scheme in the singleton, you can change the default settings globally and then continue to run the renderer to get that effect.

**Comment by mkhorton** [comment]
The downside of a singleton is if you serialize/deserialize your structure object you'll lose the custom colors, e.g. if you want to share it with someone else.

**Comment by shyamd** [comment]
Oh, I don't want to get rid of that. I'm still not sure how to deal with that. I just want some set of defaults, so we don't "have" to inject colors into the site for all situations.

**Comment by mkhorton** [comment]
The other issue with singletons is that I'm not sure how it would play out in a Dash app where you have a single singleton per process (?) and then multiple users, could get messy.

The other downside of the current method (also) is that there's just one display_color etc. given at a time. This was decided for simplicity of implementation, but you could imagine an alternative where each scene object has multiple colors + then you could switch more easily in the renderer itself to change between color schemes. That sounded a bit over-complicated though so I've avoided it for now.

**Comment by mkhorton** [comment]
Anyway, I'm filing this under "site property abuse" for now, but definitely open to better suggestions ...

**Comment by shyamd** [comment]
Yeah, I think it's not easy, but there needs to be a better way than you have to specify these two things that are not documented in pymatgen to get a renderable scene.

**Comment by shyamd** [comment]
The main restructuring for renderers is mostly done at this point, but I need to do all the aux things: tests, type hints, docstrings, etc.

**Comment by mkhorton** [comment]
Thanks. I’ll push my own updates (some of which are bug fixes, not just
shuffling of code) and the CI (setting up Percy etc) then we can look at
any merge conflicts and get this merged in

**Pull request closed without merging**
