### PR TITLE
Added Coverage

### PR DESCRIPTION
**Pull request by jmmshn**
# Added pytest coverage report.
Still need a coverage token to be set.

# Updated requirements files

# Some minor fixes to make sure all the tests passed after the requirements update.

- ~~`get_cmap` was deprecated in `matplotlib`~~
- `phonopy` is an option dependency of `pymatgen` so it should be added during testing.

### CODE REVIEW

**Comment by jmmshn** [comment]
https://github.com/materialsproject/crystaltoolkit/actions/runs/9122642016/job/25083746843?pr=391#step:8:50

I think we need to add a coverage token to this repo.

**Comment by tschaume** [comment]
@jmmshn I merged #392 and released a `v2024.5.23rc2` to test the `get_cmap` deprecation in MP.

**Comment by jmmshn** [comment]
Thanks @tschaume, can you have a look at this one for me?
I think the coverage is not triggering because we don't have the TOKEN but I do not have admin on this.

**Comment by jmmshn** [comment]
Looks like thinks should work once Ifermi is up to date with matplotlib.

**Pull request merged**
