### PR TITLE
Update for primitives

### PR DESCRIPTION
**Pull request by shyamd**
Some updates for primitive plotting

It needs some unit tests for basic functionality such as the key and merging still.

- update the ellipsoid primitive
- add in a Primitive class to define mergeability
- move key and merge code to each primitive class

### CODE REVIEW

**Comment by mkhorton** [comment]
Not the only thing that needs unit tests right now 😄

This looks great though, thanks! Let me know when it's ready to merge

**Comment by mkhorton** [comment]
Could you add a method to the `Primitive` class in this PR, something like:

```
    def get_bounding_box(self) -> List[List[float]]:
        x, y, z = zip(*self.positions)
        return [[min(x), max(x)], [min(y), max(y)], [min(z), max(z)]]
```

and then an equivalent one on `Scene`:

```
    def get_bounding_box(self) -> List[List[float]]:
        
        x_extents, y_extents, z_extents = zip(*[p.get_bounding_box() for p in self.contents])
        
        min_x = min([x[0] for x in x_extents])
        max_x = max([x[1] for x in x_extents])
        min_y = min([y[0] for y in y_extents])
        max_y = max([y[1] for y in y_extents])
        min_z = min([z[0] for z in z_extents])
        max_z = max([z[1] for z in z_extents])

        return [[min_x, max_x], [min_y, max_y], [min_z, max_z]]
```

(I'm not sure if there's a cleaner way to do this)

@JSX is having trouble setting the default zoom in the pythreejs renderer without knowing the Scene bounding box, which is what this would be useful for

**Comment by mkhorton** [comment]
Alternatively I can add a quick `Primitives` Mixin for now that just includes that, and we can resolve the merge conflict later, whichever works

**Comment by shyamd** [comment]
I can add. I just screwed up the github PR a bit and accidentally mixed in things I shouldn't have. Trying to clean this up.

Any issues with using [StandardJS](https://standardjs.com/) autoformatting?

**Comment by mkhorton** [comment]
No issues. I was using a linter but just a default one with my IDE, hadn’t
put much thought into it

**Comment by shyamd** [comment]
the JS changes are kinda mixed in with the style changes from standardJS which I'm not happy about, but at least now the extra junk isn't there.
I'm going to wait on `Renderable` until @jsx is done with the PyThreeJS implementation, so I can work with a few existing options.

**Comment by shyamd** [comment]
Oh! I also don't have tests yet... That will come, but maybe another PR since nosetests just fail horribly of now?

**Comment by mkhorton** [comment]
Yeah tests will happen. I have a plan for testing the MPComponent
subclasses. The primitives can have some more traditional unit tests
though, but no immediate rush

**Comment by mkhorton** [comment]
It’s @jmmshn btw, @jsx is someone else. I got confused because Jimmy’s name
is JSX on Github

**Comment by shyamd** [comment]
You're welcome to merge this in and fix all the things I have broken with my shitty shitty JS.

**Comment by mkhorton** [comment]
Sometimes I think we develop in the open in the hopes someone will come and
save us from ourselves :D

And thanks! Will do. Have you tested the clickable functionality?

**Comment by jmmshn** [comment]
New error since PR.
```
struct = MPRester().get_structure_by_material_id('mp-113')
smc = StructureMoleculeComponent(struct)
```
```
~/repos/js_mp/crystaltoolkit/crystal_toolkit/renderables/site.py in get_site_scene(self, connected_sites, connected_site_color, origin, ellipsoid_site_prop, all_connected_sites_present, explicitly_calculate_polyhedra_hull)
    100                 phiStart=phiStart,
    101                 phiEnd=phiEnd,
--> 102                 ellipsoids=ellipsoids,
    103             )
    104             atoms.append(sphere)

TypeError: __init__() got an unexpected keyword argument 'ellipsoids'
```

**Pull request merged**
