### PR TITLE
added a povray helper for basic visualization

### PR DESCRIPTION
**Pull request by sweitzner**
At this stage this will just provide a comparable rendering capability as the asymptote renderer.

I need to figure out how to incorporate the voxel rendering portion of the code into crystal toolkit. It was written for my own utility, so some tweaks need to be made still.

### CODE REVIEW

**Comment by sweitzner** [comment]
Forgot to add a function.

**Comment by mkhorton** [comment]
Thanks @sweitzner! Are you happy for me to merge this in for now to get started, and you can merge additional changes in later?

I see at present the main thing missing looks to be surfaces (polyhedra), which is also missing from the asymptote actually (@JSX, is there anything you need from me to add this?). And then we have the densities too.

**Comment by mkhorton** [comment]
For the camera, it looks like the only information I need to export from the interactive view is its position, since we can assume it's always looking at the origin, so I'll try and make that happen.

**Comment by sweitzner** [comment]
Yes, why don't we merge now so you can at least check to see if things are working.

I think a couple of low-hanging fruit type things that we can do in the future are:

1) Polyhedra: Someone who was working on my code with implemented this, so I think I can port that pretty easily into this code.

2) Densities:  I wrote a class that creates colormaps based on some user input. I just need to know how you guys plan on incorporating the density data and then its straightforward from there.

3) Camera settings: I have an idea of how we could set up some default views along common crystallographic axes.

**Comment by sweitzner** [comment]
Also, I tried writing a test for this, similar to test_asy.py in crystaltoolkit/tests, but when I run test_asy.py I get an error:

± python test_asy.py
Traceback (most recent call last):
  File "test_asy.py", line 2, in <module>
    from crystal_toolkit.helpers.asymptote import write_asy_file
ModuleNotFoundError: No module named 'crystal_toolkit.helpers.asymptote'

I forked the master branch, does this work for you guys?

**Comment by mkhorton** [comment]
Ah, sorry, my bad, I refactored and didn't move the test. I'm a big fan of unit testing and intend to have robust ones in this repo, but it hasn't happened yet because it's been very much in flux. Will update.

Otherwise, all else sounds good!

**Comment by sweitzner** [comment]
Ok, I figured something like that happened. Sounds good!

**Comment by mkhorton** [comment]
For 3, that would be great. We have the SymmOps via pymatgen, so presumably finding high symmetry axes might be fairly straight forward, though I don't have any specific ideas on how to implement. Finding a default "natural" angle might be a bit trickier.

**Comment by sweitzner** [comment]
Right. For starters though, we could try to just compile a list of high symmetry axes for the set of Bravais lattices and see how that fares. I figured it would be something we'd have to iterate on.

**Comment by mkhorton** [comment]
Ah, that seems better / much simpler, sounds like a plan.

**Pull request merged**
