### PR TITLE
Needs pythreejs

### PR DESCRIPTION
**Pull request by dwinston**
I couldn't try to start the server without installing pythreejs.

### CODE REVIEW

**Comment by mkhorton** [comment]
Blame @jmmshn for this ;) pythreejs should be strictly optional, but I think an import was added to the root __init__.py, so we should remove that

**Comment by mkhorton** [comment]
Comment out this line until I can merge a fix:

https://github.com/materialsproject/crystaltoolkit/blob/65b21ffcde45571826637e6747992c5d16aa7378/crystal_toolkit/__init__.py#L50

**Comment by mkhorton** [comment]
(Though also try out the pythreejs support, it's very cool!)

**Comment by dwinston** [comment]
Cool, will do. Commenting it out does not also solve #65 unfortunately.

**Comment by mkhorton** [comment]
Thanks for the PR!

**Pull request merged**
