### PR TITLE
First pass at bond order visualizations for molecules [WIP]

### PR DESCRIPTION
**Pull request by rdguha1995**
### Summary

This pull request modifies the bond order visualizations for `MoleculeGraph` in the molecules visualizer. At this point, bond orders are enforced to be integers through the `OpenBabelNN` strategy but future implementations would have interchangeable representations in which users can either choose this visualization or hover over bonds and look at the calculated bond order using the users's chosen `with_local_env_strategy`.

### TODO

- Needs a CI test run
- Future implementation of the hover strategy

### CODE REVIEW

**Comment by mkhorton** [comment]
Hi @rdguha1995, thanks for your patience. This is excellent.

I've given you permissions to merge, so please feel welcome to merge this PR :) Announcement to follow, but I'm extending permissions to merge to all collaborators (e.g. paper co-authors) to help the project feel more collaborative and reduce the delay for smaller changes, and as project maintainer I will still review prior to release as a final check.

**Review by mkhorton — APPROVED** [review]

**Comment by mkhorton** [comment]
Thanks for the merge @rdguha1995 !

**Comment by rdguha1995** [comment]
Of course @mkhorton . Really sorry for letting this slip through all this while.

**Comment by mkhorton** [comment]
No worries at all, we're all busy!

**Pull request merged**
