### PR TITLE
Add example app `matbench_dielectric_structure_on_hover.py`

### PR DESCRIPTION
**Pull request by janosh**
Addresses half of bullet point 1 in #263.

This example demonstrates how to hook up a Plotly Figure with a `StructureMoleculeComponent` that updates to show the crystal corresponding to a certain data point in the plot. The user can pick between hover and click mode using a dropdown. Hover mode updates the structure as soon as the mouse enters over a data point whereas click mode waits for a click event.

Run this app with
```sh
python crystal_toolkit/apps/examples/matbench_dielectric_structure_on_hover.py
```

https://user-images.githubusercontent.com/30958850/180328732-6f39a898-9a3f-423c-9b29-9e12801dfbb6.mp4

This PR also adds a standard set of `pre-commit` hooks similar to those used over at [`pymatgen`](https://github.com/materialsproject/pymatgen/blob/master/.pre-commit-config.yaml).

### CODE REVIEW

**Comment by janosh** [comment]
@mkhorton The data set was downloaded using `matminer` and written to disk (2.9 MB) with `pandas` to speed up subsequent runs of this app. Both `pandas` and `matminer` are new dependencies. Though only Pandas is really needed to run the app since the data file is part of this PR. Let me know if a `pandas` dependence is ok.

**Comment by mkhorton** [comment]
This looks fantastic!

Re. dependencies, `pandas` is already a dep via `pymatgen`, `matminer` has been a bit trickier in the past (via `dscribe`, `numba` dependencies, though I think `dscribe` is currently a dep here too). My suggestion would be to put `matminer` in optional dependencies only, or perhaps we can just install for the purposes of running tests.

**Comment by janosh** [comment]
Nice! Since the `matminer` import is behind a `os.path.isfile` check, it would only be needed if someone deletes the `matbench_dielectric.json.gz` file added in this PR.

Just saw `matminer` is indeed already a dependency:

https://github.com/materialsproject/crystaltoolkit/blob/6527156f9f6b9101268920e50c885a3a4d2d2937/poetry.lock#L936-L945

But I'll add it as a optional dep in `pyproject.toml` anyway.

**Comment by mkhorton** [comment]
Oh, right you are, I forgot it came in via `emmet`. There's additional context here, in that `emmet-core` is being used to provide document models for the MP database, so if we want to move the new MPRester back into pymatgen, pymatgen will need an `emmet-core` dep, but that becomes problematic with things like `matminer` there so we have some decisions to make (also why the new API has been developed separately for now).

**Comment by janosh** [comment]
Now addresses 1st bullet point in #263 fully. 2nd example can be run via 

```sh
python crystal_toolkit/apps/examples/matbench_dielectric_datatable_xrd.py
```

https://user-images.githubusercontent.com/30958850/180341888-f4782149-97c5-4128-8efd-6dc2e9e6c70c.mp4

Updating XRD component doesn't work yet due to the component itself as well as the example app having a callback setting the `data` attribute but dash allows only one calllback per target output. Currently unclear how XRD component is meant to be used as documented example `crystal_toolkit/apps/examples/diffraction_dynamic.py` crashes for me.

**Comment by mkhorton** [comment]
There's an open XRD PR at #248. Let me review and merge that and then we can fix any remaining issues.

Otherwise, this looks great! Perhaps we should link out from the matminer docs too?

**Comment by mkhorton** [comment]
Ok, one improvement here is that we do have a helper function for data tables because the default formatting is pretty poor. I'll need to upstream/update this first, but we can use it for this app.

**Comment by janosh** [comment]
Sounds good!

**Comment by janosh** [comment]
@mkhorton What's the status on the helper function for data tables? Ready to go?

**Comment by mkhorton** [comment]
Hi @janosh,

Here's the DataTable helper, which is just to go from a pandas `DataFrame` to a `dt.DataTable`. If you could add this to the PR (to `utils.py`), and then go ahead and merge this PR?

Alternatively, we do also have a more bare-bones `mpc.DataTable` component, which is used as follows:

```
mpc.DataTable(id=..., data=df.to_dict("records"), columns=..., hasHeader=.., resultLabel=...)
```

and this can be used instead. Essentially, the `mpc.DataTable` is probably preferred if you do not want advanced filtering, editable cells, or virtualization, and the `dt.DataTable` otherwise. Longterm, I'm unsure what will happen here, and if we may start to prefer just one option.

```
# TODO: move to crystal-toolkit when stable
def get_data_table(
    df=None, virtualized=True, columns=None, column_widths=None, **kwargs
):
    """
    Returns a nicely styled DataTable with sensible defaults
    for re-use.
    :param df: optional pandas DataFrame to populate DataTable
    :param virtualized: used for large tables, adds filter options
    :param columns: list of dicts with keys id and name
    :param column_widths: dict of column id to column width, e.g. "50px"
    :param kwargs: kwargs to pass to dt.DataTable
    :return: dt.DataTable
    """

    datatable_kwargs = dict(
        sort_action="native",
        row_selectable="single",
        style_as_list_view=True,
        style_cell={
            "fontFamily": "Helvetica Neue",
            "textAlign": "left",
            "whitespace": "normal",
        },
    )

    if virtualized:
        datatable_kwargs["virtualization"] = True
        datatable_kwargs["filter_action"] = "native"

    if not columns:
        columns = [{"id": column, "name": column} for column in df.columns]
    datatable_kwargs["columns"] = columns

    for k, v in kwargs.items():
        if k in datatable_kwargs:
            if isinstance(datatable_kwargs[k], dict):
                datatable_kwargs[k].update(v)
            elif isinstance(datatable_kwargs[k], list):
                datatable_kwargs[k].append(v)
            else:
                datatable_kwargs[k] = v
        else:
            datatable_kwargs[k] = v

    if df is not None:
        datatable_kwargs["data"] = df.to_dict("records")

    if column_widths:
        style_data_conditional = [
            {"if": {"column_id": column_id}, "width": column_width}
            for column_id, column_width in column_widths.items()
        ]
        if "style_data_conditional" not in datatable_kwargs:
            datatable_kwargs["style_data_conditional"] = []
        datatable_kwargs["style_data_conditional"] += style_data_conditional

    if virtualized:
        return html.Div(
            [
                dt.DataTable(**datatable_kwargs),
                html.Small(
                    dcc.Markdown(
                        'Table columns can be filtered by typing in the "filter data..." box. '
                        "Filter operators `<`, `>`, `=` and `!=` are also supported.",
                        className="mt-2",
                    )
                ),
            ]
        )
    else:
        return dt.DataTable(**datatable_kwargs)
```

**Comment by janosh** [comment]
@mkhorton Added the data table and hooked it up to the scatter plot so that hovering a scatter point will highlight the corresponding row in the data table.

https://user-images.githubusercontent.com/30958850/204675503-e00bfd73-597a-4384-bde3-8cb3275b0a72.mp4

**Comment by mkhorton** [comment]
Sweet :)

**Pull request merged**
