### PR TITLE
added option to show/hide polyhedron

### PR DESCRIPTION
**Pull request by jmmshn**

### CODE REVIEW

**Comment by jmmshn** [comment]
OK I cleaned this up a bit, I had some crap in there

**Comment by mkhorton** [comment]
Thanks! Will take a look

**Comment by mkhorton** [comment]
I'm hesitant to add a second `show_poly` UI element to the layout, because we already have it in the hide/show options (even though this does something different, from the user experience point of view it's the same, so looks like we have two identical controls), otherwise looks good.

**Comment by jmmshn** [comment]
I didn't notice that  function was added should have been more careful

**Pull request closed without merging**
