### PR TITLE
[WIP] selectively append override stylesheet(s) for embedding on MP website

### PR DESCRIPTION
**Pull request by dwinston**
@tylerhuntington222 this should reproduce the work you've done thus far in a way that is more easily comparable and adaptable. This relies (for now) on Dash loading stylesheets in lexicographic order within the `assets` folder.

@mkhorton I am following your lead in committing the `.css` and `.css.map` files generated from the `.scss`, but my preference, in general, is to not track version of "generated" files.

@tylerhuntington222 please edit the `.scss` and e.g. set up a file watcher to transpile scss->css.

### CODE REVIEW

**Comment by mkhorton** [comment]
Thanks @dwinston!

Yes, committing compiled files is probably a bad idea. This was done to make it easier to pull + run the app immediately from another host without a build step. The same is true for the compiled js.

**Comment by mkhorton** [comment]
Happy to merge btw, but I see this is a WIP -- just let me know.

**Comment by tylerhuntington222** [comment]
This looks great @dwinston. Thanks for refactoring my changes into a cleaner solution. Looks like you already created the `.scss` file to generate the necessary `.css`.

**Comment by tylerhuntington222** [comment]
@dwinston @mkhorton Any further work to be done on this that I can help with?

**Comment by dwinston** [comment]
One more thing needs doing for proper embedding: automatic iframe resizing. Illustration of problem:

need-iframe-resize

[http://davidjbradshaw.github.io/iframe-resizer/](http://davidjbradshaw.github.io/iframe-resizer/) looks like a good potential solution to this. It will require this Dash app to load a [iframeResizer.contentWindow.js](https://github.com/davidjbradshaw/iframe-resizer/blob/ac3f79d82fba68b186e9e88e14d219ad232ab283/src/iframeResizer.contentWindow.js) file that gets activated by a message from the containing page (i.e. MP).

@mkhorton please look  over the `iframeResizer.contentWindow.js` file (it has no dependencies) to verify there will be no global js namespace collisions for you.

@tylerhuntington222 could you have a go at implementing this? Add commits to the `mp-embed` branch on this repo -- not your fork -- and this PR will auto-update. You will also need to push commits to `materials_django:kill-jsmol`.

**Comment by tylerhuntington222** [comment]
@dwinston Sure, I can put a few hours into this today or tomorrow and see how far I get. We can touch base in our session on Thursday.

**Comment by dwinston** [comment]
Sounds great @tylerhuntington222 !

The other thing I thought of is using "IBM Plex Sans" `font-family` for the chemical formula bits. These can't all be captured via a class selector like `.chemform` though. I'd just search out instances of chemical formulae in the app and use a grand comma-delimited css selector to set them for now. @mkhorton any way we can slap a common class on chemical formulae?

**Comment by dwinston** [comment]
My money is on [mp-22858](http://viewer.materialsproject.org/mp-22858/) being the worst offender. Yuck.

image

**Comment by mkhorton** [comment]
Yeah, absolutely. Putting a common class on chemical formulae is no
problem, I can use `chemform` for that.

**Comment by mkhorton** [comment]
@dwinston in that screenshot it looks like the search button has become
separated from the search box? Does this look ok in person, or should I
separate those controls? (Currently they’re inheriting a Bulma grouped
control style)

**Comment by tylerhuntington222** [comment]
@mkhorton I noticed that the separation of input/search button appears to be browser-specific. There's no gap when I run the app in chrome, but it shows up in firefox. Safest bet might be to ungroup them, which I suspect would be less browser-sensitive.

**Comment by mkhorton** [comment]
Ok sounds good

**Comment by dwinston** [comment]
@mkhorton where is the functionality to load and/or toggle among multiple mp-ids, so that we can connect to existing functionality for MP users to select multiple materials from the Materials Explorer results to "edit"? I couldn't find an appropriate query parameter (akin to "token") from grepping the codebase.

**Comment by mkhorton** [comment]
search.py, it’s very minimal right now: a space delimited list of mpids
will give you a drop down to choose one of that list. This should also work
via the url path too

**Comment by dwinston** [comment]
@mkhorton I set defaultZoom in app.py now, so no change to structure.py in this PR.

**Pull request merged**
