### PR TITLE
Prevent clashing MPComponent IDs

### PR DESCRIPTION
**Pull request by janosh**
This PR fixes the error

```py
DuplicateIdError: Duplicate component id found in the initial layout: `CTstructure`
```

by appending a counter to every duplicate ID and incrementing it until the ID is unique. Not sure if this is an elegant solution. The current code explicit warns against this:

https://github.com/materialsproject/crystaltoolkit/blob/a291123709315760ce467aae29435fb8fd6da615/crystal_toolkit/core/mpcomponent.py#L194-L203

But based on the frequency with which I encounter this error in my personal use (and apparently even MP production), maybe worth a try? Perhaps @mkhorton who [wrote that comment 2 years ago](https://github.com/materialsproject/crystaltoolkit/commit/89697668242ea128a932a41a5c2cecb3a69d494c#diff-39770be153d8668c3a88c8de206238456f05cadf56a0ec5d00b48d96bbfc4ebfR214) remembers what other unexpected behavior changing the IDs might have?

<details><summary>Minimal code to trigger the error</summary>

```py
from dash import Dash, html
from pymatgen.core import Lattice, Structure

import crystal_toolkit.components as ctc
from crystal_toolkit.settings import SETTINGS

structure = Structure(
    lattice=Lattice.cubic(5),
    species=("Fe", "O"),
    coords=((0, 0, 0), (0.5, 0.5, 0.5)),
)
app = Dash()

struct_comp = ctc.StructureMoleculeComponent(id="structure", struct_or_mol=structure)
struct_comp = ctc.StructureMoleculeComponent(id="structure", struct_or_mol=structure)

app.layout = html.Div([struct_comp.layout()])

ctc.register_crystal_toolkit(app=app, layout=app.layout)


app.run(port=8000)
```

The double call to `StructureMoleculeComponent` with identical `id` seems contrived/non-sensical but is what happens naturally in contexts like a dev server where code changes trigger a hot-reload.
</details>

### CODE REVIEW

**Comment by janosh** [comment]
@yang-ruoxi Do you have another example where we could test this fix?

**Comment by yang-ruoxi** [comment]
thanks @janosh ! You can try running `mp_web/apps/materials/materials.py` or simply test the [test_basic.py](https://github.com/materialsproject/crystaltoolkit/blob/main/crystal_toolkit/apps/examples/tests/test_basic.py)

**Comment by mkhorton** [comment]
Thanks also @janosh.

The underlying issue with the counter, I think, was that a solution that might work in a single-threaded demo context might not working when deploying with gunicorn (if I remember correctly, it was some time ago).

I refer to the catch-all issue #265, but a design improvement would be to try to avoid these `str` based ids anyway, to start to use dictionary-based ids (since these can be used for pattern-matching callbacks), and perhaps to simply require the user to always specify an id. Before I left MP, I was working on a new `MPComponentAIO` class which followed the new "all-in-component" recommendations in the Dash docs, and would've made a lot of this cleaner. The only caveat holding this back is that, I think client-side callbacks still do not support pattern matching, unless this has recently changed.

**Comment by janosh** [comment]
Thanks for the update. All these caveats in different design decisions are really good to know!

> The only caveat holding this back is that, I think client-side callbacks still do not support pattern matching, unless this has recently changed.

[No change still](https://github.com/plotly/dash/issues/1461).

> Before I left MP, I was working on a new MPComponentAIO class which followed the new "all-in-component" recommendations in the Dash docs, and would've made a lot of this cleaner.

Could you push that to a branch? Maybe we can pick this up.

**Review by mkhorton — APPROVED** [review]
I think this is good to merge (without the `print` statement), as an interim fix.

**Comment by mkhorton** [comment]
> Could you push that to a branch? Maybe we can pick this up.

Yes, I'd be happy to; I'd also like to get the TaskDocument component merged (I'm not sure if this has drifted away from the MP implementation, but would be good to use it on the task detail pages), and I also have a branch which updates the example apps with `pages` support. I need to find a few hours just to tidy up a little bit before I can push however.

**Comment by janosh** [comment]
> I think this is good to merge (without the `print` statement), as an interim fix.

Oki, merging now.

> I'm not sure if this has drifted away from the MP implementation, but would be good to use it on the task detail pages

Not much if at all I think but @yang-ruoxi would know.

**Pull request merged**
